/**
 * primitives.tsx -- the small set of building blocks the product actually uses.
 *
 * Written on shadcn/ui's patterns (cva variants, `cn`, Radix underneath where a
 * component needs real accessibility behaviour) rather than generated by its
 * CLI, so each primitive carries only the variants this product needs.
 *
 * Shape and weight are load-bearing here: `Card` takes a `weight` prop because
 * the Find Leads composer and a settings row must not read as the same object.
 * Radius is a three-step scale on purpose -- 14px for a hero panel, 10px for a
 * card, 6px for a control -- not one value applied everywhere.
 */

import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

import { cn } from "@/lib/utils";
import type { StatusTone } from "@/lib/statusLabels";

// --------------------------------------------------------------------------- //
// Button
// --------------------------------------------------------------------------- //

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-control font-medium " +
    "transition-colors duration-150 ease-out disabled:pointer-events-none disabled:opacity-40 " +
    "focus-visible:outline-2 focus-visible:outline-accent focus-visible:outline-offset-2",
  {
    variants: {
      variant: {
        primary:
          "bg-accent text-accent-contrast hover:bg-accent-hover active:bg-accent",
        secondary:
          "bg-bg text-primary border border-border hover:border-border-strong hover:bg-surface-raised",
        ghost: "text-secondary hover:text-primary hover:bg-surface-raised",
        outline:
          "border border-border-strong text-primary hover:bg-surface-raised",
        danger:
          "bg-danger-muted text-danger border border-danger/30 hover:bg-danger/20",
        success:
          "bg-success-muted text-success border border-success/30 hover:bg-success/20",
      },
      size: {
        sm: "h-7 px-2.5 text-meta",
        md: "h-9 px-3.5 text-meta",
        lg: "h-11 px-5 text-body",
        icon: "h-8 w-8",
        "icon-sm": "h-7 w-7",
      },
    },
    defaultVariants: { variant: "secondary", size: "md" },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        ref={ref}
        className={cn(buttonVariants({ variant, size }), className)}
        {...props}
      />
    );
  },
);
Button.displayName = "Button";

// --------------------------------------------------------------------------- //
// Card
// --------------------------------------------------------------------------- //

const cardVariants = cva("bg-surface transition-colors", {
  variants: {
    /**
     * Importance, expressed as shape. `feature` is for the two hero surfaces
     * -- the Find Leads composer and "Needs your attention" -- and `flat` is
     * for a settings row. A flat card gets a border and no shadow; only
     * genuinely raised surfaces (popovers, the Leo panel) get the shadow.
     */
    weight: {
      feature: "rounded-panel border border-border-strong",
      standard: "rounded-card border border-border",
      flat: "rounded-control border border-border",
      bare: "rounded-card",
    },
    interactive: {
      true: "hover:border-border-strong cursor-pointer",
      false: "",
    },
  },
  defaultVariants: { weight: "standard", interactive: false },
});

export interface CardProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof cardVariants> {}

export const Card = React.forwardRef<HTMLDivElement, CardProps>(
  ({ className, weight, interactive, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(cardVariants({ weight, interactive }), className)}
      {...props}
    />
  ),
);
Card.displayName = "Card";

export function CardHeader({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("px-5 pt-4 pb-3", className)} {...props} />;
}

export function CardBody({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn("px-5 pb-5", className)} {...props} />;
}

/**
 * A section title. Deliberately not an all-caps eyebrow -- those were banned
 * for a reason. `hint` is for the one line of context a heading sometimes
 * needs, and is omitted when it does not.
 */
export function SectionTitle({
  children,
  hint,
  action,
  className,
}: {
  children: React.ReactNode;
  hint?: string;
  action?: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={cn("flex items-start justify-between gap-4", className)}>
      <div className="min-w-0">
        <h2 className="text-section font-medium text-primary">{children}</h2>
        {hint ? <p className="mt-1 text-meta text-secondary">{hint}</p> : null}
      </div>
      {action ? <div className="shrink-0">{action}</div> : null}
    </div>
  );
}

// --------------------------------------------------------------------------- //
// Badge / pill
// --------------------------------------------------------------------------- //

const badgeVariants = cva(
  "inline-flex items-center gap-1.5 whitespace-nowrap rounded-control border px-2 py-0.5 text-micro font-medium",
  {
    variants: {
      tone: {
        neutral: "border-border bg-surface-raised text-secondary",
        accent: "border-accent/25 bg-accent-soft text-accent-text",
        positive: "border-success/25 bg-success-muted text-success",
        attention: "border-warning/25 bg-warning-muted text-warning",
        negative: "border-danger/25 bg-danger-muted text-danger",
      },
    },
    defaultVariants: { tone: "neutral" },
  },
);

export function Badge({
  tone = "neutral",
  className,
  children,
  dot = false,
  ...props
}: React.HTMLAttributes<HTMLSpanElement> & {
  tone?: StatusTone;
  dot?: boolean;
}) {
  return (
    <span className={cn(badgeVariants({ tone }), className)} {...props}>
      {dot ? (
        <span
          className={cn(
            "h-1.5 w-1.5 rounded-full",
            tone === "positive" && "bg-success",
            tone === "attention" && "bg-warning",
            tone === "negative" && "bg-danger",
            tone === "accent" && "bg-accent",
            tone === "neutral" && "bg-secondary",
          )}
        />
      ) : null}
      {children}
    </span>
  );
}

/** A neutral key/value chip for dense metadata rows. */
export function MetaChip({
  label,
  value,
  mono = false,
}: {
  label: string;
  value: React.ReactNode;
  mono?: boolean;
}) {
  return (
    <span className="inline-flex items-baseline gap-1.5 text-meta">
      <span className="text-tertiary">{label}</span>
      <span className={cn("text-secondary", mono && "num")}>{value}</span>
    </span>
  );
}

// --------------------------------------------------------------------------- //
// Inputs
// --------------------------------------------------------------------------- //

export const Input = React.forwardRef<
  HTMLInputElement,
  React.InputHTMLAttributes<HTMLInputElement>
>(({ className, ...props }, ref) => (
  <input
    ref={ref}
    className={cn(
      "h-9 w-full rounded-control border border-border bg-bg px-3 text-meta text-primary",
      "placeholder:text-tertiary transition-colors duration-150",
      "hover:border-border-strong focus:border-accent focus:outline-none",
      "disabled:cursor-not-allowed disabled:opacity-50",
      className,
    )}
    {...props}
  />
));
Input.displayName = "Input";

export const Textarea = React.forwardRef<
  HTMLTextAreaElement,
  React.TextareaHTMLAttributes<HTMLTextAreaElement>
>(({ className, ...props }, ref) => (
  <textarea
    ref={ref}
    className={cn(
      "w-full rounded-control border border-border bg-bg px-3 py-2 text-meta text-primary",
      "placeholder:text-tertiary transition-colors duration-150 resize-y",
      "hover:border-border-strong focus:border-accent focus:outline-none",
      className,
    )}
    {...props}
  />
));
Textarea.displayName = "Textarea";

/** Native select, styled. A Radix select is overkill for these short lists. */
export const Select = React.forwardRef<
  HTMLSelectElement,
  React.SelectHTMLAttributes<HTMLSelectElement>
>(({ className, children, ...props }, ref) => (
  <select
    ref={ref}
    className={cn(
      "h-9 rounded-control border border-border bg-bg px-2.5 pr-7 text-meta text-primary",
      "transition-colors duration-150 hover:border-border-strong focus:border-accent focus:outline-none",
      // The chevron is a data URI, and every space in it is percent-encoded.
      // A literal space here would end the class attribute early and silently
      // discard this class and the two before it -- which is exactly what used
      // to happen.
      "appearance-none bg-[url('data:image/svg+xml;utf8,<svg%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%2212%22%20height=%2212%22%20fill=%22none%22%20stroke=%22%2364748B%22%20stroke-width=%221.5%22><path%20d=%22M3%205l3%203%203-3%22/></svg>')] bg-[right_8px_center] bg-no-repeat",
      className,
    )}
    {...props}
  >
    {children}
  </select>
));
Select.displayName = "Select";

export function Label({
  className,
  ...props
}: React.LabelHTMLAttributes<HTMLLabelElement>) {
  return (
    <label
      className={cn("block text-meta font-medium text-secondary", className)}
      {...props}
    />
  );
}

/** A labelled checkbox that reads as a control, not a form field. */
export function CheckboxRow({
  checked,
  onChange,
  label,
  hint,
  disabled,
}: {
  checked: boolean;
  onChange: (checked: boolean) => void;
  label: React.ReactNode;
  hint?: string;
  disabled?: boolean;
}) {
  return (
    <label
      className={cn(
        "flex cursor-pointer items-start gap-2.5 rounded-control border px-3 py-2 transition-colors duration-150",
        checked
          ? "border-accent/40 bg-accent-soft"
          : "border-border bg-bg hover:border-border-strong",
        disabled && "pointer-events-none opacity-50",
      )}
    >
      <input
        type="checkbox"
        checked={checked}
        disabled={disabled}
        onChange={(event) => onChange(event.target.checked)}
        className="mt-0.5 h-3.5 w-3.5 accent-[var(--accent)]"
      />
      <span className="min-w-0">
        <span className="block text-meta text-primary">{label}</span>
        {hint ? <span className="block text-micro text-secondary">{hint}</span> : null}
      </span>
    </label>
  );
}

// --------------------------------------------------------------------------- //
// Numbers
// --------------------------------------------------------------------------- //

/**
 * Every number in the product goes through here. Tabular figures are not
 * decoration: columns of scores and counts only line up if the glyphs are the
 * same width.
 */
export function Num({
  children,
  className,
  ...props
}: React.HTMLAttributes<HTMLSpanElement>) {
  return (
    <span className={cn("num", className)} {...props}>
      {children}
    </span>
  );
}

// --------------------------------------------------------------------------- //
// Progress / meters
// --------------------------------------------------------------------------- //

/** A thin horizontal meter. Used for fit scores and quota usage. */
export function Meter({
  value,
  max = 100,
  tone = "accent",
  className,
  height = 4,
}: {
  value: number;
  max?: number;
  tone?: StatusTone;
  className?: string;
  height?: number;
}) {
  const percent = max > 0 ? Math.min(100, Math.max(0, (value / max) * 100)) : 0;
  return (
    <div
      className={cn("w-full overflow-hidden rounded-full bg-surface-sunken", className)}
      style={{ height }}
      role="presentation"
    >
      <div
        className={cn(
          "h-full rounded-full transition-[width] duration-300 ease-out",
          tone === "accent" && "bg-accent",
          tone === "positive" && "bg-success",
          tone === "attention" && "bg-warning",
          tone === "negative" && "bg-danger",
          tone === "neutral" && "bg-secondary",
        )}
        style={{ width: `${percent}%` }}
      />
    </div>
  );
}

// --------------------------------------------------------------------------- //
// Separator
// --------------------------------------------------------------------------- //

export function Divider({ className }: { className?: string }) {
  return <div className={cn("h-px w-full bg-border", className)} />;
}

// --------------------------------------------------------------------------- //
// Tooltip -- a light title-attribute alternative for dense tables
// --------------------------------------------------------------------------- //

export function Hint({
  children,
  text,
}: {
  children: React.ReactNode;
  text: string;
}) {
  return (
    <span className="group/hint relative inline-flex">
      {children}
      <span
        role="tooltip"
        className={cn(
          "pointer-events-none absolute bottom-full left-1/2 z-50 mb-1.5 -translate-x-1/2",
          "whitespace-nowrap rounded-control border border-border bg-surface-raised px-2 py-1",
          "text-micro text-primary opacity-0 shadow-raised transition-opacity duration-150",
          "group-hover/hint:opacity-100",
        )}
      >
        {text}
      </span>
    </span>
  );
}
